{
 "title": "Encoding v3",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Connected Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select distinct count(w.*),now() as \"time\" from workers w where EXTRACT(EPOCH FROM now()-w.last_seen) < 600"
    }
   ]
  },
  {
   "title": "Queued Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select distinct  count(*),now() as \"time\" from job_status where status in ('queued') and notification_type='Job'"
    }
   ]
  },
  {
   "title": "In Progress Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(notification_type)FROM job_status WHERE  notification_type in ('FFMPEG','Download','Upload')  and $__timeFilter(\"event_time\")"
    }
   ]
  },
  {
   "title": "Encoding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(notification_type) FROM job_status WHERE notification_type in ('FFMPEG')  and $__timeFilter(\"event_time\")"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(notification_type) FROM job_status WHERE notification_type in ('Download') and $__timeFilter(\"event_time\")"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(notification_type) FROM job_status WHERE notification_type in ('Upload') and $__timeFilter(\"event_time\")"
    }
   ]
  },
  {
   "title": "Completed Jobs in time range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(notification_type)FROM job_status WHERE notification_type in ('Job') and status='completed' and $__timeFilter(\"event_time\")"
    }
   ]
  },
  {
   "title": "Failed Jobs in time range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(notification_type)FROM job_status WHERE notification_type in ('Job') and status='failed'  and $__timeFilter(\"event_time\")"
    }
   ]
  },
  {
   "title": "Espacio Ganado (GB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM((j.source_size - j.target_size) / 1073741824.0) AS total_space_difference_GB\r\nFROM\r\n  jobs j\r\nJOIN\r\n  job_status js ON j.id = js.job_id\r\nWHERE\r\n  $__timeFilter(js.event_time)  -- Usamos 'event_time' de 'job_status' para el filtro de tiempo\r\n  AND j.source_size > 0  -- Filtramos donde 'source_size' es mayor que 0\r\n  AND j.target_size > 0  -- Filtramos donde 'target_size' es mayor que 0\r\n"
    }
   ]
  },
  {
   "title": "Re-encodeado",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(DISTINCT je1.video_path) AS \"Total Files in This State\"\r\nFROM\r\n  job_status je1\r\nJOIN\r\n  jobs j ON je1.job_id = j.id  -- Unimos job_status con jobs para acceder a source_size y target_size\r\nWHERE\r\n  $__timeFilter(je1.event_time)  -- Aplicamos el filtro de tiempo de Grafana\r\n  AND je1.notification_type IN ('Job')  -- Filtramos los trabajos\r\n  AND je1.status = 'completed'  -- Solo trabajos completados\r\n  AND j.source_size > 0  -- Filtramos los trabajos con source_size mayor a 0\r\n  AND j.target_size = 0;  -- Filtramos los trabajos con target_size igual a 0"
    }
   ]
  },
  {
   "title": "Encodes completados por dia",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH fecha_completa AS (\r\n    SELECT generate_series(\r\n        (SELECT min(DATE(event_time)) FROM job_status WHERE status = 'completed' AND notification_type = 'Job' AND $__timeFilter(event_time)),\r\n        (SELECT max(DATE(event_time)) FROM job_status WHERE status = 'completed' AND notification_type = 'Job' AND $__timeFilter(event_time)),\r\n        '1 day'::interval\r\n    )::date AS fecha\r\n)\r\nSELECT \r\n    f.fecha,\r\n    COALESCE(COUNT(js.event_time), 0) AS num_jobs_completados\r\nFROM \r\n    fecha_completa f\r\nLEFT JOIN \r\n    job_status js\r\nON \r\n    DATE(js.event_time) = f.fecha\r\n    AND js.status = 'completed'\r\n    AND js.notification_type = 'Job'\r\n    AND $__timeFilter(js.event_time)\r\nGROUP BY \r\n    f.fecha\r\nORDER BY \r\n    f.fecha;\r\n"
    }
   ]
  },
  {
   "title": "Encodes fallados por dia",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH fecha_completa AS (\r\n    SELECT generate_series(\r\n        (SELECT min(DATE(event_time)) FROM job_status WHERE status = 'failed' AND notification_type = 'Job' AND $__timeFilter(event_time)),\r\n        (SELECT max(DATE(event_time)) FROM job_status WHERE status = 'failed' AND notification_type = 'Job' AND $__timeFilter(event_time)),\r\n        '1 day'::interval\r\n    )::date AS fecha\r\n)\r\nSELECT \r\n    f.fecha,\r\n    COALESCE(COUNT(js.event_time), 0) AS num_jobs_fallados\r\nFROM \r\n    fecha_completa f\r\nLEFT JOIN \r\n    job_status js\r\nON \r\n    DATE(js.event_time) = f.fecha\r\n    AND js.status = 'failed'\r\n    AND js.notification_type = 'Job'\r\n    AND $__timeFilter(js.event_time)\r\nGROUP BY \r\n    f.fecha\r\nORDER BY \r\n    f.fecha;\r\n"
    }
   ]
  },
  {
   "title": "Top Encoders",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select worker_name, count(worker_name) as encoded from job_status where  status in ('completed') and  notification_type='Job' and $__timeFilter(event_time) group by worker_name order by encoded desc"
    }
   ]
  },
  {
   "title": "Top Failed By Encoders",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "select worker_name, count(worker_name) as encoded from job_status where  status in ('failed') and  notification_type='Job' and $__timeFilter(event_time) group by worker_name order by encoded desc"
    }
   ]
  },
  {
   "title": "Jobs in progress",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select distinct regexp_replace(ve1.video_path, '^.+/', '') as \"File\", ve1.worker_name as \"Worker\", event_time,  ve1.notification_type as \"Action\", ve1.job_id as \"job_id\",  CASE WHEN ve1.message ~ 'progress' THEN (regexp_replace(substring(ve1.message,0,50), '^{\\\"progress\\\":\\\"?([0-9]*\\\\.?[0-9]*)\\\"?.*$', '\\\\1')) WHEN ve1.notification_type = 'Upload' THEN '99.999'  ELSE '0.0' END as progress from job_status ve1 where $__timeFilter(event_time) and notification_type in ('FFMPEG', 'Download', 'Upload', 'PGS')"
    }
   ]
  },
  {
   "title": "Completed Jobs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(worker_name) as completed, $__timeGroup(event_time, '10m') as time FROM job_status where notification_type='Job' and status='completed' GROUP BY $__timeGroup(event_time, '10m')"
    }
   ]
  },
  {
   "title": "Failed for source file size",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    worker_name, \r\n    COUNT(worker_name) AS encoded \r\nFROM \r\n    job_status \r\nWHERE \r\n    status IN ('failed') \r\n    AND notification_type = 'Job' \r\n    AND message LIKE '%source file size%' \r\n    AND $__timeFilter(event_time) \r\nGROUP BY \r\n    worker_name \r\nORDER BY \r\n    encoded DESC;\r\n"
    }
   ]
  },
  {
   "title": "Jobs Completed",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n  regexp_replace(je1.video_path, '^.+/', '') AS \"File\",  -- Extraemos el nombre del archivo\r\n  je1.worker_name AS \"Worker\",  -- Nombre del trabajador\r\n  je1.job_id AS \"job_id\",  -- ID del trabajo\r\n  je1.event_time AS \"Completed\",  -- Fecha de finalización del trabajo\r\n  (j.source_size / 1073741824.0) AS \"Source Size (GB)\",  -- Convertimos source_size a GB\r\n  (j.target_size / 1073741824.0) AS \"Target Size (GB)\",  -- Convertimos target_size a GB\r\n  ((j.source_size - j.target_size) / 1073741824.0) AS \"Size Difference (GB)\"  -- Calculamos la diferencia en GB\r\nFROM\r\n  job_status je1\r\nJOIN\r\n  jobs j ON je1.job_id = j.id  -- Unimos job_status con jobs para acceder a source_size y target_size\r\nWHERE\r\n  $__timeFilter(je1.event_time)  -- Aplicamos el filtro de tiempo de Grafana\r\n  AND je1.notification_type IN ('Job')  -- Filtramos los trabajos\r\n  AND je1.status = 'completed';  -- Solo trabajos completados\r\n"
    }
   ]
  },
  {
   "title": "Jobs Re-encodeados",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n  regexp_replace(je1.video_path, '^.+/', '') AS \"File\",  -- Extraemos el nombre del archivo\r\n  je1.worker_name AS \"Worker\",  -- Nombre del trabajador\r\n  je1.job_id AS \"job_id\",  -- ID del trabajo\r\n  je1.event_time AS \"Completed\",  -- Fecha de finalización del trabajo\r\n  (j.source_size / 1073741824.0) AS \"Source Size (GB)\",  -- Convertimos source_size a GB\r\n  (j.target_size / 1073741824.0) AS \"Target Size (GB)\",  -- Convertimos target_size a GB\r\n  ((j.source_size - j.target_size) / 1073741824.0) AS \"Size Difference (GB)\"  -- Calculamos la diferencia en GB\r\nFROM\r\n  job_status je1\r\nJOIN\r\n  jobs j ON je1.job_id = j.id  -- Unimos job_status con jobs para acceder a source_size y target_size\r\nWHERE\r\n  $__timeFilter(je1.event_time)  -- Aplicamos el filtro de tiempo de Grafana\r\n  AND je1.notification_type IN ('Job')  -- Filtramos los trabajos\r\n  AND je1.status = 'completed'  -- Solo trabajos completados\r\n  AND j.source_size > 0  -- Filtramos los trabajos con source_size mayor a 0\r\n  AND j.target_size = 0;  -- Filtramos los trabajos con target_size igual a 0\r\n"
    }
   ]
  },
  {
   "title": "Jobs en la Cola",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "select event_time as \"Cargado\",regexp_replace(video_path, '^.+/', '') as \"Video\",job_id as \"Job\" from job_status where status in ('queued') and notification_type='Job' ORDER BY event_time ASC "
    }
   ]
  },
  {
   "title": "Jobs fallados",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "select regexp_replace(video_path, '^.+/', '') as \"Video\",event_time as \"Fecha fallo\", worker_name as \"Worker\", message as \"Mensaje de error\" from job_status where status in ('failed') and notification_type='Job' and $__timeFilter(\"event_time\") ORDER BY event_time DESC "
    }
   ]
  },
  {
   "title": "Estados",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "select regexp_replace(video_path, '^.+/', '') as \"Video\",event_time as \"Fecha fallo\", worker_name as \"Worker\", message as \"Mensaje de error\", status as \"Estado\" from job_status where notification_type='Job' and $__timeFilter(\"event_time\") ORDER BY event_time DESC "
    }
   ]
  }
 ]
}