name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      _EXPERIMENTAL_DAGGER_CACHE_CONFIG: type=gha,scope=dagger-lint-${{ github.ref }},mode=max
      _EXPERIMENTAL_DAGGER_SHUTDOWN_TIMEOUT: 180s
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mage lint:check
