name: CI
on:  
  push:
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: build server docker
        uses: docker/build-push-action@v1
        with:
          dockerfile: server/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: segator/transcoderd
          tags: latest
      - name: build worker docker
        uses: docker/build-push-action@v1
        with:
          dockerfile: worker/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: segator/transcoderw
          tags: latest        
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.3
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch
    - name: Build Server
      run: go run build.go build server
    - name: Build Workers
      run: go run build.go build worker
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: build/transcoder*   
    - name: Upload Release Asset
      if: github.event_name == 'push'
      id: upload-release-asset 
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:        
        prerelease: true
        name: ${{ steps.branch.outputs.branch }}        
        tag_name: ${{ github.ref }}
        files: build/transcoder*
