name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - uses: actions/checkout@v2
    - name: Prepare
      run: go build -o builder.bin build.go
    - name: Build Server
      run: sudo ./builder.bin build server
    - name: Build Workers
      run: sudo ./builder.bin build worker   
    - name: Publish Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: binaries
        path: ./build/transcoder*
