name: CI
on:
  push:
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: build server docker
        uses: docker/build-push-action@v1
        with:
          dockerfile: server/dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: segator/transcoderd
          tags: latest
      - name: build worekr docker
        uses: docker/build-push-action@v1
        with:
          dockerfile: worker/dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: segator/transcoderw
          tags: latest        
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - uses: actions/checkout@v2
    - name: Prepare      
      run: |        
        go build -o builder.bin build.go  
        chmod 777 builder.bin    
    - name: Build Server
      run: |
        echo $GOSRC
        echo $GOPATH
        echo $GOBIN
        PATH=${PATH}:`go env GOPATH`/bin
        echo $PATH
        sudo echo $PATH
        sudo ./builder.bin build server
    - name: Build Workers
      run: sudo ./builder.bin build worker   
    - name: Publish Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: binaries
        path: ./build/transcoder*
